# 100 numpy exercises
#### 1. Import the numpy package under the name `np` (★☆☆)

`提示: import … as`

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

`提示: np.__version__, np.show_config)`

In [2]:
print(np.__version__)
np.show_config

1.18.5


<function numpy.__config__.show()>

#### 3. Create a null vector of size 10 (★☆☆)

`hint: np.zeros`

In [3]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

`hint: size, itemsize`

In [4]:
z = np.zeros((10, 10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

`hint: np.info`

In [5]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

`hint: array[4]`

In [6]:
ans = np.zeros(10)
ans[4] = 1
ans

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

`hint: arange`

In [7]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

`hint: array[::-1]`

In [8]:
z = np.arange(50)
z = z[: :-1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

`hint: reshape`

In [9]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

`hint: np.nonzero`

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

`hint: np.eye`

In [11]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

`hint: np.random.random`

In [12]:
z = np.random.random((3,3,3))
z

array([[[0.20076232, 0.81910672, 0.56250499],
        [0.09956241, 0.35256134, 0.32595597],
        [0.67738801, 0.516568  , 0.92261896]],

       [[0.83400568, 0.50199924, 0.49662071],
        [0.19073156, 0.36565531, 0.58633749],
        [0.83114383, 0.21845551, 0.85042465]],

       [[0.22100682, 0.81186007, 0.20803371],
        [0.84142569, 0.50887652, 0.92607884],
        [0.68873866, 0.36108469, 0.27673765]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

`hint: min, max`

In [13]:
z = np.random.random((10,10))
print(z)
print(z.min())
print(z.max())

[[0.76645183 0.78609832 0.70376627 0.58361705 0.21405917 0.47626275
  0.97337668 0.05878677 0.07470434 0.91529048]
 [0.55056537 0.1228886  0.87712085 0.78701012 0.7032546  0.37817044
  0.15626328 0.84101568 0.01540835 0.17289019]
 [0.23791031 0.1792464  0.65127399 0.05771024 0.47229735 0.47370168
  0.9398193  0.67124347 0.64735058 0.65933849]
 [0.90662686 0.94247061 0.69600751 0.40512616 0.27312985 0.68499985
  0.57889765 0.92828319 0.97871565 0.20012908]
 [0.79808955 0.74282895 0.48087603 0.4241668  0.99803527 0.9996983
  0.4196703  0.69338284 0.97432924 0.52081151]
 [0.78275822 0.38036227 0.04286029 0.41621028 0.06632816 0.81308421
  0.06734326 0.49498609 0.58460338 0.84376169]
 [0.75671566 0.25318503 0.03505358 0.3709321  0.25770981 0.22435794
  0.57762076 0.10833651 0.18554587 0.66617097]
 [0.64181046 0.50882497 0.13206384 0.57955641 0.09045385 0.29276616
  0.58711321 0.81210846 0.96368239 0.36319747]
 [0.45597311 0.40355633 0.3315131  0.6024646  0.19415839 0.35801339
  0.1789022  

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

`hint: mean`

In [14]:
z = np.random.random(30)
print(z.mean())

0.46936565604358643


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

`hint: array[1:-1, 1:-1]`

In [15]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

`hint: np.pad`

In [17]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

`hint: NaN = not a number, inf = infinity`

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

`hint: np.diag`

In [19]:
z = np.diag(1 + np.arange(4),k = -1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

`hint: array[::2]`

In [21]:
z = np.zeros((8,8),dtype = int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

# numpy中 : 与 :: 的区别
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x[1:5])#打印index为1~5的数组，范围是左闭右开
print(x[3:])#打印index=3之后的数组，包含index=3
print(x[:9])#打印index=9之前的数组，不包含index=9
print(x[1:-2])#打印index=1到倒数第2个index之间的数组
print(x[-9:-2])#打印倒数第9个index和倒数第2个index之间的数组，左开右闭

print(x[1::3])#以index=1为起始位置，间隔3
print(x[::3])#默认从index=0开始，间隔3
print(x[3::])#和[3:]一样
print(x[::-1])#反向打印数据，从最后一个index开始，间隔为1
print(x[::-3])#反向打印数据，从最后一个index开始，间隔为3
print(x[7:2:-1])#反向打印index=2(不包含)到index=7之间的数据

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[2 3 4 5]
[ 4  5  6  7  8  9 10 11 12]
[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10]
[ 2  5  8 11]
[ 1  4  7 10]
[ 4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]
[12  9  6  3]
[8 7 6 5 4]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

`hint: np.unravel_index`

In [22]:
print(np.unravel_index(99,(6,7,8)))# 返回indices中的元素在维度为dims的数组中的索引值，默认按元组的形式返回

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

`hint: np.tile`

In [23]:
z = np.tile(np.array([[0,1],[1,0]]),(4,4)) #行重复4次，列重复4次
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

`hint: (x -mean)/std`

In [25]:
z = np.random.random((5,5))
z = (z - np.mean(z)) / (np.std(z))
z

array([[ 0.64641722,  0.44408064,  0.11133373, -0.94858689,  1.2826405 ],
       [ 1.35391871, -0.16106478,  0.00259111, -0.21646587, -1.42839837],
       [-0.54435818, -1.05731769, -0.90959204,  0.09302851,  0.33752933],
       [-1.44251417, -0.58599518,  0.24907157,  1.46141085,  1.77699981],
       [ 1.49071033, -1.51417741, -1.42275098, -0.10783464,  1.08932389]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

`hint: np.dtype`

In [26]:
color = np.dtype([
    ("r",np.ubyte,1),
    ("g",np.ubyte,1),
    ("b",np.ubyte,1),
    ("a",np.ubyte,1)])

D:\Apps\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

`hint:`

In [27]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

`hint: >, <`

In [28]:
z = np.arange(11)
z[(3 < z) & (z < 8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

`hint: np.sum`

In [29]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

`No hints provided...`

In [32]:
Z**Z
# 2 << Z >> 2 # wrong
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z # wrong

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 28. What are the result of the following expressions? (★☆☆)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

`No hints provided...`

In [33]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


D:\Apps\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\Apps\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

`hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [34]:
# numpy.random.uniform(low=0, high=1, size)
# 功能介绍：从 low 到 high 中随机采样，注意左闭右开。得到的结果在 low 到 high 上满足均匀分布，size：输出样本数目
Z = np.random.uniform(-10,+10,10) 

# np.copysign(ndarray1, ndarray2) 将参数2中的符号赋予参数1
# np.ceil(ndarray) 计算大于等于改值的最小整数

print(np.copysign(np.ceil(np.abs(Z)), Z))

# np.floor(ndarray) 计算小于等于该值的最大整数
# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-8.  8. -1.  7.  9. -1. -3.  5. -1. -6.]
[-8.  8. -1.  7.  9. -1. -3.  5. -1. -6.]


#### 30. How to find common values between two arrays? (★☆☆)

`hint: np.intersect1d`

In [36]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
# randint(begin,end,num=1) 从给定的begin和end随机选取num个整数
# np.intersect1d( ndarray1, ndarray2) 返回二者的交集并排序
print(np.intersect1d(z1,z2))

[0 1 4 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

`hint: np.seterr, np.errstate`

In [37]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

`hint: imaginary number`

In [38]:
np.sqrt(-1) == np.emath.sqrt(-1)

D:\Apps\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

`hint: np.datetime64, np.timedelta64`

In [40]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2021-02-01
2021-02-02
2021-02-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

`hint: np.arange(dtype=datetime64['D'])`

In [41]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

`hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

In [42]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A,B,out = B)
np.divide(A,2,out = A)
np.negative(A,out = A)
np.multiply(A,B,out = A)
A

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

`hint: %, np.floor, astype, np.trunc`

In [43]:
z = np.random.uniform(0,10,10)
print(z - z%1)
print(z // 1)
print(np.floor(z))
print(z.astype(int))
print(np.trunc(z))

[3. 8. 3. 9. 3. 6. 7. 9. 4. 3.]
[3. 8. 3. 9. 3. 6. 7. 9. 4. 3.]
[3. 8. 3. 9. 3. 6. 7. 9. 4. 3.]
[3 8 3 9 3 6 7 9 4 3]
[3. 8. 3. 9. 3. 6. 7. 9. 4. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

`hint: np.arange`

In [45]:
z = np.zeros((5,5))
z += np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

`hint: np.fromiter`

In [47]:
def generator():
    for x in range(10):
        yield x

# yield 是一个类似 return 的关键字，迭代一次遇到yield时就返回yield后面(右边)的值。
# 重点是：下一次迭代时，从上一次迭代遇到的yield后面的代码(下一行)开始执行。
# return 的作用：如果没有 return，则默认执行至函数完毕，返回的一 般是  yield的变量
# np.fromiter 从可迭代对象创建新的1维数组
z = np.fromiter(generator(),dtype = float,count = -1)
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

`hint: np.linspace`

In [49]:
z = np.linspace(0,1,11,endpoint = False)[1:]
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

`hint: sort`

In [50]:
z = np.random.random(10)
z.sort()
z

array([0.33926114, 0.43587301, 0.54261255, 0.589625  , 0.64063813,
       0.66279782, 0.69195355, 0.70027239, 0.74302279, 0.90903581])

#### 41. How to sum a small array faster than np.sum? (★★☆)

`hint: np.add.reduce`

In [51]:
z = np.arange(10)
np.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

`hint: np.allclose, np.array_equal`

In [52]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

`hint: flags.writeable`

In [53]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

`hint: np.sqrt, np.arctan2`

In [54]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.77823538 0.99583886 0.92821029 1.11980208 1.00445301 0.76219169
 1.32242414 1.08895493 0.75402107 1.04535583]
[0.65876942 0.27827888 0.7805817  0.52447449 0.14098076 0.82628556
 0.73218501 0.67001897 0.6164506  0.87064383]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

`hint: argmax`

In [55]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.75646128 0.94211233 0.10046937 0.74103356 0.75230031 0.24992727
 0.83275921 0.33828928 0.56958834 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

`hint: np.meshgrid`

In [56]:
# np.meshgrid 生成网格点坐标矩阵

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

`hint: np.subtract.outer`

In [57]:
# np.subtract.outer(b,a)是b[:,None]-a的函数对应
# 其含义是：有两个向量a、b，要实现a中的每个元素与b中的每个元素进行比较

# np.linalg.det():矩阵求行列式
# np.linalg.inv()：矩阵求逆
# np.linalg.norm():求范数

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

`hint: np.iinfo, np.finfo, eps`

In [58]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

`hint: np.set_printoptions`

In [59]:
np.set_printoptions(threshold=float("inf")) # 打印全部
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

`hint: argmin`

In [60]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

49


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

`hint: dtype`

In [62]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


D:\Apps\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

`hint: np.atleast_2d, T, np.sqrt`

In [63]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
# np.atleast_2d 将输入的数组转化为至少两维

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.4652142  0.25436187 0.25837482 0.58099252 0.55833571
  0.30847915 0.29373256 0.57027925 0.2286076 ]
 [0.4652142  0.         0.69738585 0.7206557  0.81367227 0.10076136
  0.73289727 0.70875257 0.22361835 0.28386657]
 [0.25436187 0.69738585 0.         0.08515631 0.45471991 0.78189709
  0.31820482 0.07416944 0.8230217  0.42321035]
 [0.25837482 0.7206557  0.08515631 0.         0.53884718 0.81058873
  0.23933017 0.15730047 0.82518611 0.45972   ]
 [0.58099252 0.81367227 0.45471991 0.53884718 0.         0.85479429
  0.77044144 0.38155073 1.01476914 0.56150372]
 [0.55833571 0.10076136 0.78189709 0.81058873 0.85479429 0.
  0.83240934 0.78741089 0.25819967 0.36040666]
 [0.30847915 0.73289727 0.31820482 0.23933017 0.77044144 0.83240934
  0.         0.39236961 0.7711849  0.53493667]
 [0.29373256 0.70875257 0.07416944 0.15730047 0.38155073 0.78741089
  0.39236961 0.         0.85105976 0.42717214]
 [0.57027925 0.22361835 0.8230217  0.82518611 1.01476914 0.25819967
  0.7711849  0.85105

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

`hint: view and [:] =`

In [64]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[63 99 61 10 61 80 77 86 14 21]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

`hint: np.genfromtxt`

In [65]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

`hint: np.ndenumerate, np.ndindex`

In [66]:
# np.ndenumerate 返回一个迭代器，产生一对数组坐标和值

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

`hint: np.meshgrid, np.exp`

In [67]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

`hint: np.put, np.random.choice`

In [68]:
#  np.put(a, ind, v, mode=‘raise’) 参数解释 ：1、a 就是目标数组 这里就是5*5的零数组 2、ind是目标数组的位置 3、v是你要加入的值
# 注意：在此函数中a是扁平化的(无论是一维还是二维)

# numpy.random.choice(a, size=None, replace=True, p=None) 参数解释：1、从a(只要是ndarray都可以，但必须是一维的)中随机抽取数字
# 2、size：取得数字的个数 3、replace:True表示可以取相同数字，False表示不可以取相同数字 4、数组p：描述数组a中每一个元素取得的概率。
# 举例 np.random.choice(range(25),3,replace = False)//从25的范围内去3个不同的数

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

`hint: mean(axis=,keepdims=)`

In [69]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.14098146  0.20872435  0.1343724  -0.47066966 -0.06725417 -0.15042348
   0.31209458  0.26589608 -0.19022501  0.09846636]
 [-0.00653547  0.07036208 -0.43327919  0.13397805  0.27198859  0.47401773
   0.08097279  0.08411282 -0.3227325  -0.3528849 ]
 [ 0.12382035 -0.34757064  0.42278843 -0.44900847 -0.1411346   0.50116004
   0.24212908 -0.35293732 -0.4205674   0.42132052]
 [ 0.2548742   0.02255454  0.37176199 -0.18133648 -0.10030519 -0.06703359
   0.32153506 -0.39615337  0.00827348 -0.23417065]
 [ 0.11612717  0.55478943  0.08000008 -0.18875576 -0.01066316  0.06116952
  -0.32529483 -0.00466762  0.02934545 -0.31205028]]


#### 59. How to sort an array by the nth column? (★★☆)

`hint: argsort`

In [70]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[6 5 0]
 [8 0 2]
 [8 0 3]]
[[8 0 2]
 [8 0 3]
 [6 5 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

`hint: any, ~`

In [71]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

`hint: np.abs, argmin, flat`

In [72]:
# flat返回的是一个迭代器，可以用for访问数组每一个元素
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5442859501788653


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

`hint: np.nditer`

In [73]:
# np.nditer 有效的多维迭代器对象，可以遍历数组
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

`hint: class method`

In [74]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

`hint: np.bincount | np.add.at`

In [75]:
# np.bincount 返回值中的每个bin，给出了它的索引值在x中出现的次数（在默认权重下）；返回值中的每个bin，给出了它的索引值，
# 由于在x中出现在不同位置所导致权重不同，而计算的加权和。其中，索引的长度可由minlength规定。
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# np.add.at 将传入的数组中制定下标位置的元素加上指定的值
np.add.at(Z, I, 1)
print(Z)

[4. 2. 6. 2. 1. 2. 1. 4. 3. 5.]
[ 7.  3. 11.  3.  1.  3.  1.  7.  5.  9.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

`hint: np.bincount`

In [76]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

`hint: np.unique`

In [77]:
# np.unique 去除数组中的重复数字，并进行排序之后输出

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

`hint: sum(axis=(-2,-1))`

In [78]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[60 77 61 39]
 [54 61 68 54]
 [66 38 68 54]]
[[60 77 61 39]
 [54 61 68 54]
 [66 38 68 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

`hint: np.bincount`

In [79]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.62380447 0.42801387 0.4273121  0.39286606 0.45751295 0.50721397
 0.38820934 0.43310254 0.6650784  0.49117048]
0    0.623804
1    0.428014
2    0.427312
3    0.392866
4    0.457513
5    0.507214
6    0.388209
7    0.433103
8    0.665078
9    0.491170
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

`hint: np.diag`

In [80]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.99415129, 0.99166035, 1.07521776, 1.60626594, 1.73603655])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

`hint: array[::4]`

In [81]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

`hint: array[:, :, None]`

In [82]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

`hint: array[[]] = array[[]]`

In [83]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

`hint: repeat, np.roll, np.sort, view, np.unique`

In [84]:
# np.roll(a, shift, axis=None)
# 意思是将a，沿着axis的方向，滚动shift长度

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 47) ( 1, 58) ( 9, 15) ( 9, 17) ( 9, 47) ( 9, 80) (10, 21) (10, 56)
 (11, 24) (11, 45) (11, 68) (11, 91) (15, 80) (17, 47) (21, 56) (24, 91)
 (40, 45) (40, 55) (41, 78) (41, 88) (45, 55) (45, 68) (47, 58) (65, 76)
 (65, 93) (76, 93) (78, 88) (79, 88) (79, 98) (88, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

`hint: np.repeat`

In [85]:
# np.repeat 用于将numpy数组重复
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

`hint: np.cumsum`

In [86]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

`hint: from numpy.lib import stride_tricks`

In [87]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

`hint: np.logical_not, np.negative`

In [88]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.18068396, -0.77098563,  0.98991678, -0.93186496, -0.32269725,
       -0.67260869, -0.35244344,  0.21594203,  0.71644684,  0.90729472,
       -0.43164163,  0.37725802,  0.86853153, -0.32249925, -0.32329803,
        0.79478704, -0.94674545,  0.28230654, -0.90968595, -0.19035287,
       -0.35221058, -0.87195255,  0.1930602 , -0.48682194, -0.50063477,
       -0.79331373, -0.56304451, -0.27940703,  0.61560574, -0.55877799,
       -0.34063795, -0.87402457, -0.44516417, -0.38867748,  0.36508997,
        0.88446752, -0.46108201, -0.80327755, -0.59100604,  0.38903817,
       -0.80402597,  0.97949186, -0.56720264,  0.03549636, -0.12488947,
        0.57640151, -0.77341038, -0.86264728, -0.02440207, -0.87846721,
        0.07325522, -0.05502939,  0.5289353 ,  0.27795148,  0.65277747,
        0.31670391, -0.14425048, -0.2095557 ,  0.74769394, -0.15643088,
        0.11395065, -0.50383982,  0.8795915 , -0.62218784,  0.5110961 ,
       -0.22264968,  0.7834089 ,  0.02926092,  0.52050289,  0.23

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

`No hints provided...`

In [89]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 5.93560018 11.48513894  9.373802    4.44139452 11.16904901  5.93707385
 13.99042451  5.23305847  4.2857223   9.69407859]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

`No hints provided...`

In [92]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.42209488  7.92378985  5.04021455  0.7741986  12.64501958  6.82860676
   1.7603304   4.18419291  2.4863679  10.92959547]
 [ 3.89368822  1.17413813  0.86481387 10.80771707 10.95292221  3.16772184
  11.80302635 16.64592585  7.64902004 10.32987918]
 [ 0.95424877  2.93338816  1.15684209  4.0868178   9.91280807  0.62451779
   5.52505328  9.78195053  3.76266573  8.72644332]
 [ 9.96233269 11.63764494 13.48799027  2.90854389  4.21453463 12.56274238
   1.31911212 11.11290431 16.84087741  5.01290757]
 [ 4.51844777  3.94293639  1.12989377  0.67442813  8.95408788  3.09063081
   1.02817823  4.95966945  1.22840708  7.37639721]
 [10.64836997  2.44338127  1.67117807  6.81167564  5.09333417  3.66197516
   5.35283082  0.77920146  0.55180188  3.10284869]
 [ 6.60252246  4.21503897  4.1272568  12.01205111 14.28467495  0.72284401
  13.62841353 17.30426991  5.24188174 13.65278557]
 [ 2.10130736  9.62931854  6.57193903  1.48453382 13.95924849  8.6440821
   1.41394485  3.19991458  4.30233854 12.13457631]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

`hint: minimum maximum`

In [93]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[6 5 8 8 4 6 8 4 9 6]
 [4 3 3 3 0 8 4 0 0 3]
 [5 9 9 7 4 6 7 0 1 5]
 [1 8 8 2 4 6 0 3 1 3]
 [3 2 8 7 2 0 6 1 0 6]
 [4 6 3 9 2 9 4 8 1 9]
 [5 2 1 9 0 2 6 2 8 4]
 [5 6 7 5 5 5 3 4 5 4]
 [3 5 2 2 7 1 0 7 7 8]
 [4 6 4 4 7 4 8 0 6 6]]
[[0 0 0 0 0]
 [0 6 5 8 8]
 [0 4 3 3 3]
 [0 5 9 9 7]
 [0 1 8 8 2]]


D:\Apps\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

`hint: stride_tricks.as_strided`

In [94]:
# stride_tricks.as_strided 对一个矩阵进行切块
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

`hint: np.linalg.svd`

In [95]:
# np.linalg.svd 总共有三个返回值u,s,v；其中s是对矩阵a的奇异值分解。s除了对角元素不为0，其他元素都为0，
# 并且对角元素从大到小排列。s中有n个奇异值，一般排在后面的比较接近0，所以仅保留比较大的r个奇异值。
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

`hint: np.bincount, argmax`

In [96]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

`hint: stride_tricks.as_strided`

In [97]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 4 4]
   [4 0 3]
   [3 3 0]]

  [[4 4 0]
   [0 3 1]
   [3 0 1]]

  [[4 0 1]
   [3 1 1]
   [0 1 0]]

  [[0 1 3]
   [1 1 2]
   [1 0 4]]

  [[1 3 2]
   [1 2 0]
   [0 4 0]]

  [[3 2 0]
   [2 0 2]
   [4 0 4]]

  [[2 0 3]
   [0 2 3]
   [0 4 1]]

  [[0 3 1]
   [2 3 4]
   [4 1 2]]]


 [[[4 0 3]
   [3 3 0]
   [2 0 4]]

  [[0 3 1]
   [3 0 1]
   [0 4 3]]

  [[3 1 1]
   [0 1 0]
   [4 3 0]]

  [[1 1 2]
   [1 0 4]
   [3 0 2]]

  [[1 2 0]
   [0 4 0]
   [0 2 2]]

  [[2 0 2]
   [4 0 4]
   [2 2 1]]

  [[0 2 3]
   [0 4 1]
   [2 1 1]]

  [[2 3 4]
   [4 1 2]
   [1 1 0]]]


 [[[3 3 0]
   [2 0 4]
   [1 1 3]]

  [[3 0 1]
   [0 4 3]
   [1 3 0]]

  [[0 1 0]
   [4 3 0]
   [3 0 3]]

  [[1 0 4]
   [3 0 2]
   [0 3 1]]

  [[0 4 0]
   [0 2 2]
   [3 1 3]]

  [[4 0 4]
   [2 2 1]
   [1 3 0]]

  [[0 4 1]
   [2 1 1]
   [3 0 0]]

  [[4 1 2]
   [1 1 0]
   [0 0 3]]]


 [[[2 0 4]
   [1 1 3]
   [1 4 2]]

  [[0 4 3]
   [1 3 0]
   [4 2 2]]

  [[4 3 0]
   [3 0 3]
   [2 2 1]]

  [[3 0 2]
   [0 3 1]
   [2 1 0]]

  [[0 2 2]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

`hint: class method`

In [98]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5 13  4 12 10]
 [13  0  0 13  9]
 [ 4  0  0 42  3]
 [12 13 42  0  6]
 [10  9  3  6  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

`hint: np.tensordot`

In [99]:
# np.tensordot 沿指定轴计算张量点积
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

`hint: np.add.reduceat`

In [100]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

`No hints provided...`

In [101]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

`hint: np.argsort | np.argpartition`

In [102]:
# np.argsort 返回对数组排序的索引
# np.argpartition 返回值是一个列表，int参数指定列表中该index位置是该数组中i-th小的数，即：排在该index前面的都小于该数，排在后面的都大于等于该数
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9997 9995 9996 9998]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

`hint: np.indices`

In [103]:
# np.indices 返回一个给定形状数组的序号网格数组，可以用于提取数组元素或对数组进行切片使用
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

`hint: np.core.records.fromarrays`

In [104]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

`hint: np.power, *, np.einsum`

In [105]:
# np.einsum 将向量插入某一行或列
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.1 s ± 809 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.04 s ± 101 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
733 ms ± 118 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

`hint: np.where`

In [106]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

`No hints provided...`

In [107]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 2 4]
 [2 0 2]
 [3 0 1]
 [3 1 0]
 [2 0 3]
 [2 1 1]
 [2 0 4]
 [2 3 2]
 [0 4 2]
 [3 4 0]]
[[0 2 4]
 [2 0 2]
 [3 0 1]
 [3 1 0]
 [2 0 3]
 [2 1 1]
 [2 0 4]
 [2 3 2]
 [0 4 2]
 [3 4 0]]
[[0 2 4]
 [2 0 2]
 [3 0 1]
 [3 1 0]
 [2 0 3]
 [2 1 1]
 [2 0 4]
 [2 3 2]
 [0 4 2]
 [3 4 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

`hint: np.unpackbits`

In [108]:
# np.unpackbits 将uint8数组的元素解压缩为二进制值输出数组
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

`hint: np.ascontiguousarray | np.unique`

In [109]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 1]]
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

`hint: np.einsum`

In [110]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.78495942, 0.26959613, 0.18649882, 0.47012408, 0.54592121,
        0.68011894, 0.21585062, 0.58019476, 0.25946733, 0.57292177],
       [0.7250109 , 0.24900667, 0.17225563, 0.43422   , 0.50422839,
        0.62817724, 0.19936579, 0.53588443, 0.23965142, 0.52916688],
       [0.2452786 , 0.0842415 , 0.05827584, 0.14690107, 0.17058562,
        0.21251878, 0.06744748, 0.18129518, 0.08107653, 0.17902257],
       [0.16081907, 0.05523368, 0.03820907, 0.09631698, 0.11184596,
        0.13933981, 0.04422254, 0.11886778, 0.05315854, 0.11737772],
       [0.21951992, 0.07539463, 0.05215583, 0.1314738 , 0.15267105,
        0.19020048, 0.06036428, 0.16225592, 0.07256203, 0.16022197],
       [0.43493961, 0.14938102, 0.10333748, 0.26049192, 0.30249049,
        0.37684836, 0.11960107, 0.32148119, 0.14376873, 0.31745128],
       [0.80238961, 0.27558257, 0.19064007, 0.48056328, 0.55804351,
        0.69522113, 0.22064363, 0.59307812, 0.26522886, 0.58564362],
       [0.00434123, 0.00149101, 0.0010314

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

`hint: np.cumsum, np.interp`

In [112]:
# np.interp 返回离散数据的一维分段线性插值结果
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

`hint: np.logical_and.reduce, np.mod`

In [113]:
# np.logical_and.reduce add.reduce()相当于sum()
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

`hint: np.percentile`

In [114]:
# np.percentile 找到一组数的分位数值，如四分位数等(具体什么位置根据自己定义)
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.12552049  0.22380825]
