# Input and Output

In [1]:
from __future__ import print_function
import numpy as np

In [2]:
author = "kyubyong. https://github.com/Kyubyong/numpy_exercises"

In [3]:
np.__version__

'1.18.5'

In [4]:
from datetime import date
print(date.today())

2021-02-02


## NumPy binary files (NPY, NPZ)

Q1. Save x into `temp.npy` and load it.

In [5]:
x = np.arange(10)
np.save('temp.npy', x) # Actually you can omit the extension. If so, it will be added automatically.

# Check if there exists the 'temp.npy' file.
import os
if os.path.exists('temp.npy'):
    x2 = np.load('temp.npy')
    print(np.array_equal(x, x2))


True


Q2. Save x and y into a single file 'temp.npz' and load it.

In [6]:
x = np.arange(10)
y = np.arange(11, 20)
np.savez('temp.npz', x=x, y=y)
# np.savez_compressed('temp.npz', x=x, y=y) # If you want to save x and y into a single file in compressed .npz format.
with np.load('temp.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(np.array_equal(x, x2))
    print(np.array_equal(y, y2))


True
True


## Text files

Q3. Save x to 'temp.txt' in string format and load it.

In [7]:
x = np.arange(10).reshape(2, 5)
header = 'num1 num2 num3 num4 num5'
np.savetxt('temp.txt', x, fmt="%d", header=header) 
np.loadtxt('temp.txt')

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

Q4. Save `x`, `y`, and `z` to 'temp.txt' in string format line by line, then load it.

In [8]:
x = np.arange(10)
y = np.arange(11, 21)
z = np.arange(22, 32)
np.savetxt('temp.txt', (x, y, z), fmt='%d')
np.loadtxt('temp.txt')

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [22., 23., 24., 25., 26., 27., 28., 29., 30., 31.]])

Q5. Convert `x` into bytes, and load it as array.

In [9]:
x = np.array([1, 2, 3, 4])
x_bytes = x.tostring() # Don't be misled by the function name. What it really does is it returns bytes.
x2 = np.fromstring(x_bytes, dtype=x.dtype) # returns a 1-D array even if x is not.
print(np.array_equal(x, x2))


True


D:\Apps\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  This is separate from the ipykernel package so we can avoid doing imports until


Q6. Convert `a` into an ndarray and then convert it into a list again.

In [10]:
a = [[1, 2], [3, 4]]
x = np.array(a)
a2 = x.tolist()
print(a == a2)

True


## String formatting¶

Q7. Convert `x` to a string, and revert it.

In [11]:
x = np.arange(10).reshape(2,5)
x_str = np.array_str(x)
print(x_str, "\n", type(x_str))
x_str = x_str.replace("[", "") # [] must be stripped
x_str = x_str.replace("]", "")
x2 = np.fromstring(x_str, dtype=x.dtype, sep=" ").reshape(x.shape)
assert np.array_equal(x, x2)



[[0 1 2 3 4]
 [5 6 7 8 9]] 
 <class 'str'>


## Text formatting options

Q8. Print `x` such that all elements are displayed with precision=1, no suppress.

In [12]:
x = np.random.uniform(size=[10,100])
np.set_printoptions(precision=1, threshold=np.nan, suppress=True)
print(x)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

## Base-n representations

Q9. Convert 12 into a binary number in string format.

In [13]:
out1 = np.binary_repr(12)
out2 = np.base_repr(12, base=2)
assert out1 == out2 # But out1 is better because it's much faster.
print(out1)

1100


Q10. Convert 12 into a hexadecimal number in string format.

In [14]:
np.base_repr(1100, base=16)

'44C'